language: csharp 
solution: Pkcs11Interop.sln

before_install:
  - sudo apt-get install nunit-console
before_script:
  - cd src\Pkcs11Interop
  - nuget restore Pkcs11Interop.sln
after_script:
  - nunit-console /Pkcs11InteropTests/bin/Release/Pkcs11InteropTests.dll
  

