language: csharp 
solution: ./src/Pkcs11Interop/Pkcs11Interop.sln

before_install:
  - sudo apt-get install nunit-console 
before_script:
  - nuget restore ./src/Pkcs11Interop/Pkcs11Interop.sln
after_script:
  - xbuild ./src/Pkcs11Interop/Pkcs11Interop.sln
  - nunit-console ./src/Pkcs11Interop/Pkcs11InteropTests/bin/Release/Pkcs11InteropTests.dll
  

