language: csharp 
solution: Pkcs11Interop.sln

before_install:
  - sudo apt-get install nunit-console
  - cd /src/Pkcs11Interop
before_script:
  - nuget restore Pkcs11Interop.sln
after_script:
  - nunit-console /Pkcs11InteropTests/bin/Release/Pkcs11InteropTests.dll
  

